<?php

$ranksetNames["NSMBW"] = "NSMBW";

$ranksetData["NSMBW"] = array(
	array("num" => 0, "image" => '', "text" => 'Non-poster'),
	array("num" => 1, "image" => '', "text" => 'Newcomer'),
	array("num" => 10, "image" => 'microgoomba.png', "text" => 'Micro Goomba'),
	array("num" => 20, "image" => 'goomba.png', "text" => 'Goomba'),
	array("num" => 35, "image" => 'paragoomba.png', "text" => 'Paragoomba'),
	array("num" => 50, "image" => 'chestnut_goomba.png', "text" => 'Chestnut Goomba'),
	array("num" => 65, "image" => 'giantgoomba.png', "text" => 'Giant Goomba'),
	array("num" => 80, "image" => 'koopa_green_shell.png', "text" => 'Green Shell'),
	array("num" => 100, "image" => 'koopa_red_shell.png', "text" => 'Red Shell'),
	array("num" => 110, "image" => 'koopa_green.png', "text" => 'Koopa Troopa'),
	array("num" => 120, "image" => 'koopa_red.png', "text" => 'Red Koopa Troopa'),
	array("num" => 140, "image" => 'fencekoopa_vert.png', "text" => 'Fence Koopa'),
	array("num" => 160, "image" => 'mechakoopa.png', "text" => 'Mecha Koopa'),
	array("num" => 180, "image" => 'amp.png', "text" => 'Amp'),
	array("num" => 200, "image" => 'bobomb.png', "text" => 'Bob-omb'),
	array("num" => 240, "image" => 'boo.png', "text" => 'Boo'),
	array("num" => 260, "image" => 'buzzy_beetle.png', "text" => 'Buzzy Beetle'),
	array("num" => 280, "image" => 'broozer.png', "text" => 'Broozer'),
	array("num" => 300, "image" => 'bulber.png', "text" => 'Bulber'),
	array("num" => 325, "image" => 'angrymoon.png', "text" => 'Angry Moon'),
	array("num" => 350, "image" => 'angrysun.png', "text" => 'Angry Sun'),
	array("num" => 375, "image" => 'blooper.png', "text" => 'Blooper'),
	array("num" => 400, "image" => 'blooper_babies.png', "text" => 'Blooper With Babies'),
	array("num" => 425, "image" => 'bramball.png', "text" => 'Bramball'),
	array("num" => 450, "image" => 'cheep_red.png', "text" => 'Red Cheep-Cheep'),
	array("num" => 475, "image" => 'cheep_yellow.png', "text" => 'Yellow Cheep-Cheep'),
	array("num" => 500, "image" => 'cheep_green.png', "text" => 'Green Cheep-Cheep'),
	array("num" => 525, "image" => 'cheep_giant_red.png', "text" => 'Giant Red Cheep-Cheep'),
	array("num" => 550, "image" => 'cheep_giant_yellow.png', "text" => 'Giant Yellow Cheep-Cheep'),
	array("num" => 575, "image" => 'cheep_giant_green.png', "text" => 'Giant Green Cheep-Cheep'),
	array("num" => 600, "image" => 'crow.png', "text" => 'Crowber'),
	array("num" => 625, "image" => 'e_switch.png', "text" => 'Small Switch'),
	array("num" => 650, "image" => 'e_switch_lg.png', "text" => 'Big Switch'),
	array("num" => 675, "image" => 'boomerangbro.png', "text" => 'Boomerang Bro'),
	array("num" => 700, "image" => 'hammerbro.png', "text" => 'Hammer Brother'),
	array("num" => 725, "image" => 'firebro.png', "text" => 'Fire Brother'),
	array("num" => 750, "image" => 'icebro.png', "text" => 'Ice Brother'),
	array("num" => 775, "image" => 'sledgebro.png', "text" => 'Sledge Brother'),
	array("num" => 800, "image" => 'firetrap_pipe_up.png', "text" => 'Venus Fire Trap'),
	array("num" => 825, "image" => 'fishbones.png', "text" => 'Fish Bone'),
	array("num" => 850, "image" => 'foo.png', "text" => 'Foo'),
	array("num" => 875, "image" => 'fuzzy.png', "text" => 'Fuzzy'),
	array("num" => 900, "image" => 'fuzzy_bear.png', "text" => 'Giant Fuzzy'),
	array("num" => 925, "image" => 'gabon_r.png', "text" => 'Spike'),
	array("num" => 950, "image" => 'gabon_d.png', "text" => 'Stone Spike'),
	array("num" => 970, "image" => 'drybones.png', "text" => 'Dry Bones'),
	array("num" => 1000, "image" => 'giant_drybones.png', "text" => 'Giant Dry Bones'),
	array("num" => 1050, "image" => 'spike_ball.png', "text" => 'Spike Ball'),
	array("num" => 1100, "image" => 'giant_spike_ball.png', "text" => 'Giant Spike Ball'),
	array("num" => 1150, "image" => 'ground_piranha.png', "text" => 'Piranha Plant'),
	array("num" => 1200, "image" => 'huckit_crab.png', "text" => 'Huckit Crab'),
	array("num" => 1250, "image" => 'jellybeam.png', "text" => 'Jelly Beam'),
	array("num" => 1300, "image" => 'lakitu.png', "text" => 'Lakitu'),
	array("num" => 1350, "image" => 'little_mouser_0.png', "text" => 'Mouser'),
	array("num" => 1400, "image" => 'monty_mole.png', "text" => 'Monty Mole'),
	array("num" => 1450, "image" => 'rocky_wrench.png', "text" => 'Rocky Wrench'),
	array("num" => 1500, "image" => 'podoboo.png', "text" => 'Podoboo'),
	array("num" => 1550, "image" => 'porcu_puffer.png', "text" => 'Porcu Puffer'),
	array("num" => 1650, "image" => 'redcoinring.png', "text" => 'Red Coin Ring'),
	array("num" => 1700, "image" => 'ShyGuy0.png', "text" => 'Shy Guy'),
	array("num" => 1750, "image" => 'ShyGuy1.png', "text" => 'Blue Shy Guy'),
	array("num" => 1800, "image" => 'ShyGuy3.png', "text" => 'Yellow Shy Guy'),
	array("num" => 1850, "image" => 'ShyGuy4.png', "text" => 'Pink Shy Guy'),
	array("num" => 1900, "image" => 'ShyGuy5.png', "text" => 'Green Shy Guy'),
	array("num" => 2000, "image" => 'bigredguy.png', "text" => 'Big Red Guy'),
	array("num" => 2100, "image" => 'samurai_guy.png', "text" => 'Samurshai'),
	array("num" => 2200, "image" => 'spiketop.png', "text" => 'Spike Top'),
	array("num" => 2300, "image" => 'spiny.png', "text" => 'Spiny'),
	array("num" => 2400, "image" => 'spiny_cheep.png', "text" => 'Spiny Cheep'),
	array("num" => 2500, "image" => 'starcoin.png', "text" => 'Star Coin'),
	array("num" => 2600, "image" => 'swooper.png', "text" => 'Swooper'),
	array("num" => 2700, "image" => 'toad.png', "text" => 'Toad'),
	array("num" => 2800, "image" => 'topman.png', "text" => 'Topman'),
	array("num" => 2900, "image" => 'wiggler.png', "text" => 'Wiggler'),
	array("num" => 3000, "image" => 'Larry_Koopa.png', "text" => 'Larry Koopa'),
	array("num" => 3100, "image" => 'Roy_Koopa.png', "text" => 'Roy Koopa'),
	array("num" => 3200, "image" => 'Lemmy_Koopa.png', "text" => 'Lemmy Koopa'),
	array("num" => 3300, "image" => 'Wendy_Koopa.png', "text" => 'Wendy Koopa'),
	array("num" => 3400, "image" => 'Iggy_Koopa.png', "text" => 'Iggy Koopa'),
	array("num" => 3500, "image" => 'Morton_Koopa.png', "text" => 'Morton Koopa'),
	array("num" => 3600, "image" => 'Ludwig_Von_Koopa.png', "text" => 'Ludwig von Koopa'),
	array("num" => 3700, "image" => 'Kamek.png', "text" => 'Kamek'),
	array("num" => 3800, "image" => 'Bowser.png', "text" => 'Bowser Koopa'),
	array("num" => 3900, "image" => 'minimario.png', "text" => 'Mini Mario'),
	array("num" => 4000, "image" => 'smallmario.png', "text" => 'Small Mario'),
	array("num" => 4100, "image" => 'supermario.png', "text" => 'Super Mario'),
	array("num" => 4200, "image" => 'icemario.png', "text" => 'Ice Mario'),
	array("num" => 4400, "image" => 'firemario.png', "text" => 'Fire Mario'),
	array("num" => 4600, "image" => 'propeller.png', "text" => 'Propeller Mario'),
	array("num" => 4800, "image" => 'penguinmario.png', "text" => 'Penguin Mario'),
	array("num" => 5000, "image" => 'starmario.png', "text" => 'Star Mario'),
	
);
