<?php
// Zelda Ranket from Acmlmboard 2 by Fyxe. Converted from Acmlmboard format to BlargBoard format by AlphaTech
$ranksetNames["zelda"] = "Zelda"; 
$ranksetData["zelda"] = array(
array("num" => 0, "image" => '', "text" => 'Non-poster'), 
array("num" => 1, "image" => '', "text" => 'Newcomer'), 
array("num" => 10, "image" => 'Octoballoon.gif', "text" => 'Octoballoon'), 
array("num" => 20, "image" => 'Octorok.gif', "text" => 'Octorok'), 
array("num" => 30, "image" => 'Onoff.gif', "text" => 'Onoff'), 
array("num" => 40, "image" => 'Poe.gif', "text" => 'Poe'), 
array("num" => 50, "image" => 'Popo.gif', "text" => 'Popo'), 
array("num" => 60, "image" => 'PurpleLeever.gif', "text" => 'Purple Leever'), 
array("num" => 70, "image" => 'RabbitLink.gif', "text" => 'Rabit Link'), 
array("num" => 80, "image" => 'Rat.gif', "text" => 'Rat'), 
array("num" => 90, "image" => 'Raven.gif', "text" => 'Raven'), 
array("num" => 100, "image" => 'RedMailLink.gif', "text" => 'Red Mail Link'), 
array("num" => 110, "image" => 'RedStalfos.gif', "text" => 'Red Stalfos'), 
array("num" => 120, "image" => 'RedTektite.gif', "text" => 'Red Tekite'), 
array("num" => 130, "image" => 'RedTorosu.gif', "text" => 'Red Torosu'), 
array("num" => 140, "image" => 'Rocklops.gif', "text" => 'Rocklops'), 
array("num" => 150, "image" => 'Ropa.gif', "text" => 'Ropa'), 
array("num" => 160, "image" => 'Rope.gif', "text" => 'Rope'), 
array("num" => 170, "image" => 'SandCrab.gif', "text" => 'Sand Crab'), 
array("num" => 180, "image" => 'Slime.gif', "text" => 'Slime'), 
array("num" => 190, "image" => 'SnapDragon.gif', "text" => 'Snap Dragon'), 
array("num" => 200, "image" => 'Stalfos.gif', "text" => 'Stalfos'), 
array("num" => 210, "image" => 'Sukarurope.gif', "text" => 'Sukarurope'), 
array("num" => 220, "image" => 'Surarok.gif', "text" => 'Surarok'), 
array("num" => 230, "image" => 'Tektite.gif', "text" => 'Tektite'), 
array("num" => 240, "image" => 'Tendoru.gif', "text" => 'Tendoru'), 
array("num" => 250, "image" => 'TheAdventureOfLink.gif', "text" => 'The Adventure of Link'), 
array("num" => 260, "image" => 'Torosu.gif', "text" => 'Torosu'), 
array("num" => 270, "image" => 'Vire.gif', "text" => 'Vire'), 
array("num" => 280, "image" => 'Vitreous.gif', "text" => 'Vitreous'), 
array("num" => 290, "image" => 'YellowStalfos.gif', "text" => 'Yellow Stalfos'), 
array("num" => 300, "image" => 'Zelda.gif', "text" => 'Zelda'), 
array("num" => 310, "image" => 'Zirro.gif', "text" => 'Zirro'), 
array("num" => 320, "image" => 'Zora.gif', "text" => 'Zora')
);
