<?php
// Kirby Ranket from Acmlmboard 2 by YoshiDude. Converted from Acmlmboard format to BlargBoard format by AlphaTech
$ranksetNames["kirby"] = "Kirby"; 
$ranksetData["kirby"] = array(
array("num" => 0, "image" => '', "text" => 'Non-poster'),  
array("num" => 5, "image" => 'acro.gif', "text" => 'Acro'),                                                                                                             
array("num" => 10, "image" => 'biospark.gif', "text" => 'BioSpark'),                                                                                       
array("num" => 15, "image" => 'birdon.gif', "text" => 'Birdon'),                                                                                   
array("num" => 20, "image" => 'bladeknight.gif', "text" => 'Blade Knight'),                                                                                     
array("num" => 25, "image" => 'blipper.gif', "text" => 'Blipper'),                                                                                
array("num" => 30, "image" => 'bobo.gif', "text" => 'Bobo'),                                                                                    
array("num" => 35, "image" => 'boboo.gif', "text" => 'Boboo'),                                                                                       
array("num" => 40, "image" => 'bomber.gif', "text" => 'Bomber'),                                                                                                                
array("num" => 45, "image" => 'bonkers.gif', "text" => 'Bonkers'),                                                                                                               
array("num" => 50, "image" => 'bouncy.gif', "text" => 'Bouncy'),                                                                                    
array("num" => 55, "image" => 'brontoburt.gif', "text" => 'Bronto Burt'),                                                                                     
array("num" => 60, "image" => 'broomhatter.gif', "text" => 'Broom Hatter'),                                                                                 
array("num" => 65, "image" => 'bugzzy.gif', "text" => 'Bugzzy'),                                                                                
array("num" => 70, "image" => 'burninleo.gif', "text" => 'Burnin Leo'),                                                                                     
array("num" => 75, "image" => 'butch.gif', "text" => 'Butch'),                                                                                  
array("num" => 80, "image" => 'cappy.gif', "text" => 'Cappy'),                                                                                      
array("num" => 85, "image" => 'capsulej.gif', "text" => 'Capsulej'),                                                                                      
array("num" => 90, "image" => 'captainstitch.gif', "text" => 'Captain Stitch'),                                                                                   
array("num" => 95, "image" => 'chefkawasaki.gif', "text" => 'Chef Kawaski'),                                                                              
array("num" => 100, "image" => 'chilly.gif', "text" => 'Chilly'),                                                                               
array("num" => 105, "image" => 'clockwork.gif', "text" => 'Clock Work'),                                                                                     
array("num" => 110, "image" => 'coney.gif', "text" => 'Coney'),                                                                                  
array("num" => 115, "image" => 'coo.gif', "text" => 'Coo'),                                                                                      
array("num" => 120, "image" => 'darkmatter.gif', "text" => 'Dark Matter'),                                                                                        
array("num" => 125, "image" => 'dynababy.gif', "text" => 'Dyna Baby'),                                                                               
array("num" => 130, "image" => 'flamemane.gif', "text" => 'Flamemane'),                                                                                    
array("num" => 135, "image" => 'frosty.gif', "text" => 'Frosty'),                                                                                   
array("num" => 140, "image" => 'gator.gif', "text" => 'Gator'),                                                                                     
array("num" => 145, "image" => 'giantwaddledee.gif', "text" => 'Giant Waddledee'),                                                                                      
array("num" => 150, "image" => 'gim.gif', "text" => 'Gim'),                                                                             
array("num" => 155, "image" => 'glunk.gif', "text" => 'Glunk'),                                                                                        
array("num" => 160, "image" => 'gooey.gif', "text" => 'Gooey'),                                                                                      
array("num" => 165, "image" => 'gordo.gif', "text" => 'Gordo'),                                                                                      
array("num" => 170, "image" => 'grizzo.gif', "text" => 'Grizzo'),                                                                                      
array("num" => 175, "image" => 'gungun.gif', "text" => 'Gun Gun'),                                                                                     
array("num" => 180, "image" => 'haboki.gif', "text" => 'Haboki'),                                                                                     
array("num" => 185, "image" => 'jumpershoot.gif', "text" => 'Jumper Shoot'),                                                                                     
array("num" => 190, "image" => 'kabu.gif', "text" => 'Kabu'),                                                                                
array("num" => 195, "image" => 'karateman.gif', "text" => 'Karate Man'),                                                                                       
array("num" => 200, "image" => 'kine.gif', "text" => 'Kine'),                                                                                  
array("num" => 205, "image" => 'kingdedede.gif', "text" => 'King Dedede'),                                                                                       
array("num" => 210, "image" => 'kirbyadventure.gif', "text" => 'Kirby Adventure'),                                                                                 
array("num" => 215, "image" => 'kirbybreak.gif', "text" => 'Kirby Break'),                                                                             
array("num" => 220, "image" => 'kirbydreamland3.gif', "text" => 'Kirby Dreamland 3'),                                                                                  
array("num" => 225, "image" => 'kirbyplush.gif', "text" => 'Kirby Plush'),                                                                           
array("num" => 230, "image" => 'kirbysamurai.gif', "text" => 'Kirby Samurai'),                                                                                                          
array("num" => 235, "image" => 'kirbyship.gif', "text" => 'Kirby Ship'),                                                                               
array("num" => 240, "image" => 'kirbysnooze.gif', "text" => 'Kirby Snooze'),                                                                                  
array("num" => 245, "image" => 'kirbystrut.gif', "text" => 'Kirby Strut'),                                                                                
array("num" => 250, "image" => 'kirbywarpstar.gif', "text" => 'Kirby Warpstar'),                                                                                 
array("num" => 255, "image" => 'knucklejoe.gif', "text" => 'Knuckle Joe'),                                                                              
array("num" => 260, "image" => 'kracko.gif', "text" => 'Kracko'),                                                                                 
array("num" => 265, "image" => 'kruff.gif', "text" => 'Kruff'),                                                                                     
array("num" => 270, "image" => 'lunarknight.gif', "text" => 'Lunark Knight'),                                                                                      
array("num" => 275, "image" => 'masher.gif', "text" => 'Masher'),                                                                                
array("num" => 280, "image" => 'masterhand.gif', "text" => 'Master Hand'),                                                                                     
array("num" => 285, "image" => 'metaknight.gif', "text" => 'Meta Knight'),                                                                                 
array("num" => 290, "image" => 'mrbright.gif', "text" => 'Mr. Bright'),                                                                                 
array("num" => 295, "image" => 'mrshine.gif', "text" => 'Mr. Shine'),                                                                                   
array("num" => 300, "image" => 'mumbies.gif', "text" => 'Mumbies'),                                                                                    
array("num" => 310, "image" => 'noddy.gif', "text" => 'Noddy'),                                                                                    
array("num" => 320, "image" => 'paintroller.gif', "text" => 'Paintroller'),                                                                                      
array("num" => 330, "image" => 'panic.gif', "text" => 'Panic'),                                                                                
array("num" => 340, "image" => 'parasolwdee.gif', "text" => 'Parasolwdee'),                                                                                      
array("num" => 350, "image" => 'phanphan.gif', "text" => 'Phan Phan'),                                                                                
array("num" => 360, "image" => 'plasmawhisp.gif', "text" => 'Plasma Whisp'),                                                                                   
array("num" => 370, "image" => 'poppybros.gif', "text" => 'Poppy Bros'),                                                                                
array("num" => 380, "image" => 'poppybrossr.gif', "text" => 'Poppy Brossr'),                                                                                  
array("num" => 390, "image" => 'rick.gif', "text" => 'Rick'),                                                                                                                  
array("num" => 400, "image" => 'rocky.gif', "text" => 'Rocky'),                                                                                       
array("num" => 410, "image" => 'scarfy.gif', "text" => 'Scarfy'),                                                                                      
array("num" => 420, "image" => 'scarfyprovoked.gif', "text" => 'Scarfy Provoked'),                                                                                     
array("num" => 430, "image" => 'simirror.gif', "text" => 'Simirror'),                                                                             
array("num" => 440, "image" => 'sirkibble.gif', "text" => 'Sir Kibble'),                                                                                   
array("num" => 450, "image" => 'sparky.gif', "text" => 'Sparky'),                                                                                  
array("num" => 460, "image" => 'squishy.gif', "text" => 'Squishy'),                                                                                     
array("num" => 470, "image" => 'starorb.gif', "text" => 'Star Orb'),                                                                                    
array("num" => 480, "image" => 'stave.gif', "text" => 'Stave'),                                                                                    
array("num" => 490, "image" => 'tac.gif', "text" => 'Tac'),                                                                                      
array("num" => 500, "image" => 'togezo.gif', "text" => 'Togezo'),                                                                                        
array("num" => 510, "image" => 'tooky.gif', "text" => 'Tooky'),                                                                                     
array("num" => 520, "image" => 'tosstortoise.gif', "text" => 'Toss Tortoise'),                                                                                      
array("num" => 530, "image" => 'tweet.gif', "text" => 'Tweet'),                                                                               
array("num" => 540, "image" => 'twister.gif', "text" => 'Twister'),                                                                                      
array("num" => 550, "image" => 'ufo.gif', "text" => 'UFO'),                                                                                    
array("num" => 560, "image" => 'waddledee.gif', "text" => 'Waddledee'),                                                                                        
array("num" => 570, "image" => 'waddledoo.gif', "text" => 'Waddledoo'),                                                                                  
array("num" => 580, "image" => 'walkie.gif', "text" => 'Walkie'),                                                                                  
array("num" => 590, "image" => 'wheeliebig.gif', "text" => 'Wheelie Big'),                                                                                     
array("num" => 600, "image" => 'wheelierider.gif', "text" => 'Wheelie Rider'),
array("num" => 700, "image" => 'whispywoods.gif', "text" => 'Whispy Woods')
);
