<?php

$ranksetNames["mario"] = "Mario";

$ranksetData["mario"] = array(
	array("num" => 0, "image" => '', "text" => 'Non-poster'),
	array("num" => 1, "image" => '', "text" => 'Newcomer'),
	array("num" => 10, "image" => 'microgoomba.png', "text" => 'Micro-Goomba'),
	array("num" => 20, "image" => 'goomba.png', "text" => 'Goomba'),
	array("num" => 35, "image" => 'redgoomba.png', "text" => 'Red Goomba'),
	array("num" => 50, "image" => 'redparagoomba.png', "text" => 'Red Paragoomba'),
	array("num" => 65, "image" => 'paragoomba.png', "text" => 'Paragoomba'),
	array("num" => 80, "image" => 'shyguy.png', "text" => 'Shyguy'),
	array("num" => 100, "image" => 'koopa.png', "text" => 'Koopa'),
	array("num" => 120, "image" => 'redkoopa.png', "text" => 'Red Koopa'),
	array("num" => 140, "image" => 'paratroopa.png', "text" => 'Paratroopa'),
	array("num" => 160, "image" => 'redparatroopa.png', "text" => 'Red Paratroopa'),
	array("num" => 180, "image" => 'cheepcheep.png', "text" => 'Cheep-cheep'),
	array("num" => 200, "image" => 'redcheepcheep.png', "text" => 'Red Cheep-cheep'),
	array("num" => 225, "image" => 'ninji.png', "text" => 'Ninji'),
	array("num" => 250, "image" => 'flurry.png', "text" => 'Flurry'),
	array("num" => 275, "image" => 'snifit.png', "text" => 'Snifit'),
	array("num" => 300, "image" => 'porcupo.png', "text" => 'Porcupo'),
	array("num" => 325, "image" => 'panser.png', "text" => 'Panser'),
	array("num" => 350, "image" => 'mole.png', "text" => 'Mole'),
	array("num" => 375, "image" => 'buzzybeetle.png', "text" => 'Buzzy Beetle'),
	array("num" => 400, "image" => 'nipperplant.png', "text" => 'Nipper Plant'),
	array("num" => 425, "image" => 'bloober.png', "text" => 'Bloober'),
	array("num" => 450, "image" => 'busterbeetle.png', "text" => 'Buster Beetle'),
	array("num" => 475, "image" => 'beezo.png', "text" => 'Beezo'),
	array("num" => 500, "image" => 'bulletbill.png', "text" => 'Bullet Bill'),
	array("num" => 525, "image" => 'rex.png', "text" => 'Rex'),
	array("num" => 550, "image" => 'lakitu.png', "text" => 'Lakitu'),
	array("num" => 575, "image" => 'spiny.png', "text" => 'Spiny'),
	array("num" => 600, "image" => 'bobomb.png', "text" => 'Bob-Omb'),
	array("num" => 625, "image" => 'drybones.png', "text" => 'Dry Bones'),
	array("num" => 650, "image" => 'cobrat.png', "text" => 'Cobrat'),
	array("num" => 675, "image" => 'pokey.png', "text" => 'Pokey'),
	array("num" => 700, "image" => 'spike.png', "text" => 'Spike'),
	array("num" => 725, "image" => 'melonbug.png', "text" => 'Melon Bug'),
	array("num" => 750, "image" => 'lanternghost.png', "text" => 'Lantern Ghost'),
	array("num" => 775, "image" => 'fuzzy.png', "text" => 'Fuzzy'),
	array("num" => 800, "image" => 'bandit.png', "text" => 'Bandit'),
	array("num" => 830, "image" => 'superkoopa.png', "text" => 'Super Koopa'),
	array("num" => 860, "image" => 'redsuperkoopa.png', "text" => 'Red Super Koopa'),
	array("num" => 900, "image" => 'boo.png', "text" => 'Boo'),
	array("num" => 925, "image" => 'boo.png', "text" => 'Boo'),
	array("num" => 950, "image" => 'fuzzball.png', "text" => 'Fuzz Ball'),
	array("num" => 1000, "image" => 'boomerangbrother.png', "text" => 'Boomerang Brother'),
	array("num" => 1050, "image" => 'hammerbrother.png', "text" => 'Hammer Brother'),
	array("num" => 1100, "image" => 'firebrother.png', "text" => 'Fire Brother'),
	array("num" => 1150, "image" => 'firesnake.png', "text" => 'Fire Snake'),
	array("num" => 1200, "image" => 'giantgoomba.png', "text" => 'Giant Goomba'),
	array("num" => 1250, "image" => 'giantkoopa.png', "text" => 'Giant Koopa'),
	array("num" => 1300, "image" => 'giantredkoopa.png', "text" => 'Giant Red Koopa'),
	array("num" => 1350, "image" => 'giantparatroopa.png', "text" => 'Giant Paratroopa'),
	array("num" => 1400, "image" => 'giantredparatroopa.png', "text" => 'Giant Red Paratroopa'),
	array("num" => 1450, "image" => 'chuck.png', "text" => 'Chuck'),
	array("num" => 1500, "image" => 'thwomp.png', "text" => 'Thwomp'),
	array("num" => 1550, "image" => 'bossbass.png', "text" => 'Boss Bass'),
	array("num" => 1600, "image" => 'volcanolotus.png', "text" => 'Volcano Lotus'),
	array("num" => 1650, "image" => 'lavalotus.png', "text" => 'Lava Lotus'),
	array("num" => 1700, "image" => 'ptooie.png', "text" => 'Ptooie'),
	array("num" => 1800, "image" => 'sledgebrother.png', "text" => 'Sledge Brother'),
	array("num" => 1900, "image" => 'boomboom.png', "text" => 'Boomboom'),
	array("num" => 2000, "image" => 'birdo.png', "text" => 'Birdo'),
	array("num" => 2100, "image" => 'redbirdo.png', "text" => 'Red Birdo'),
	array("num" => 2200, "image" => 'greenbirdo.png', "text" => 'Green Birdo'),
	array("num" => 2300, "image" => 'larrykoopa.png', "text" => 'Larry Koopa'),
	array("num" => 2400, "image" => 'mortonkoopa.png', "text" => 'Morton Koopa'),
	array("num" => 2500, "image" => 'wendykoopa.png', "text" => 'Wendy Koopa'),
	array("num" => 2600, "image" => 'iggykoopa.png', "text" => 'Iggy Koopa'),
	array("num" => 2700, "image" => 'roykoopa.png', "text" => 'Roy Koopa'),
	array("num" => 2800, "image" => 'lemmykoopa.png', "text" => 'Lemmy Koopa'),
	array("num" => 2900, "image" => 'ludwigvonkoopa.png', "text" => 'Ludwig Von Koopa'),
	array("num" => 3000, "image" => 'triclyde.png', "text" => 'Triclyde'),
	array("num" => 3100, "image" => 'magikoopa.png', "text" => 'Magikoopa'),
	array("num" => 3200, "image" => 'wart.png', "text" => 'Wart'),
	array("num" => 3300, "image" => 'babybowser.png', "text" => 'Baby Bowser'),
	array("num" => 3400, "image" => 'kingbowserkoopa.png', "text" => 'King Bowser Koopa'),
	array("num" => 3500, "image" => 'yoshi.png', "text" => 'Yoshi'),
	array("num" => 3600, "image" => 'yellowyoshi.png', "text" => 'Yellow Yoshi'),
	array("num" => 3700, "image" => 'blueyoshi.png', "text" => 'Blue Yoshi'),
	array("num" => 3800, "image" => 'redyoshi.png', "text" => 'Red Yoshi'),
	array("num" => 3900, "image" => 'kingyoshi.png', "text" => 'King Yoshi'),
	array("num" => 4000, "image" => 'babymario.png', "text" => 'Baby Mario'),
	array("num" => 4100, "image" => 'luigi.png', "text" => 'Luigi'),
	array("num" => 4200, "image" => 'mario.png', "text" => 'Mario'),
	array("num" => 4300, "image" => 'superluigi.png', "text" => 'Super Luigi'),
	array("num" => 4400, "image" => 'supermario.png', "text" => 'Super Mario'),
	array("num" => 4500, "image" => 'fireluigi.png', "text" => 'Fire Luigi'),
	array("num" => 4600, "image" => 'firemario.png', "text" => 'Fire Mario'),
	array("num" => 4700, "image" => 'capeluigi.png', "text" => 'Cape Luigi'),
	array("num" => 4800, "image" => 'capemario.png', "text" => 'Cape Mario'),
	array("num" => 4900, "image" => 'starluigi.png', "text" => 'Star Luigi'),
	array("num" => 5000, "image" => 'starmario.png', "text" => 'Star Mario')
);
